### ISSUE TITLE
error when running in google search console

### ISSUE THREAD

**Issue by drma-dev** [jsakamoto/Toolbelt.Blazor.PWA.Updater#15]
@jsakamoto I applied the new version of Blazor Wasm PreRendering to my main project and it kept giving errors. After analyzing it for some time, I discovered that it was because of this project.

In the test project that I had uploaded, this is the result:
![image](https://github.com/jsakamoto/Toolbelt.Blazor.PWA.Updater/assets/12803050/97f7cf8c-5c81-4ae7-9b29-b8dcacaf8ee2)
It gives a generic Blazor error and then tries to download some DLLs, but it works and Google can process it.

but in my main project, there is a javascript error in PWA.Updater, and the execution is stopped, it does not continue with the dll downloads and the page is not processed.
![image](https://github.com/jsakamoto/Toolbelt.Blazor.PWA.Updater/assets/12803050/b72fc669-d2b1-4032-91c8-59457521177e)
```
Uncaught (in promise) Error: Rejected at wrsParams.serviceWorkers.navigator.serviceWorker.register (<anonymous>:13:648) at https://www.streamingdiscovery.com/_content/Toolbelt.Blazor.PWA.Updater.Service/script.min.js:1:825 at https://www.streamingdiscovery.com/_content/Toolbelt.Blazor.PWA.Updater.Service/script.min.js:1:865 at https://www.streamingdiscovery.com/_content/Toolbelt.Blazor.PWA.Updater.Service/script.min.js:1:896 at https://www.streamingdiscovery.com/_content/Toolbelt.Blazor.PWA.Updater.Service/script.min.js:1:919 at https://www.streamingdiscovery.com/_content/Toolbelt.Blazor.PWA.Updater.Service/script.min.js:1:948
:12
```

**Comment by drma-dev** [comment]
Nevermind. the problem is something else.
